version: 0.2

phases:
  build:
    commands:
      - sbt -Dsbt.log.noformat=true assets
#      - sbt -Dsbt.log.noformat=true fullOptJS
artifacts:
  files:
    - '**/*'
  base-directory:
    'web/target/web/public/main/'
cache:
  paths:
    - '/root/.sbt/**/*'
    - '/root/.ivy2/cache/**/*'
    - '/root/.cache/**/*'
    - 'target/**/*'
    - 'js/target/**/*'
    - 'web/target/**/*'
